#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

BRANCH_REGEX="^(main|develop|dev)|([0-9]{1,}-(feat|fix|refactor|docs|chore|test)-[a-zA-Z-]{2,})$"

if ! echo "$BRANCH_NAME" | grep -Eq "$BRANCH_REGEX";
then
  echo "-"
  echo "Error: Branch name '$BRANCH_NAME' does not match the required pattern."
  echo "-"
  echo "Allowed patterns are:"
  echo "  - main"
  echo "  - develop or dev"
  echo "  - <number>-feat-<description>"
  echo "  - <number>-fix-<description>"
  echo "  - <number>-refactor-<description>"
  echo "  - <number>-docs-<description>"
  echo "  - <number>-chore-<description>"
  echo "  - <number>-test-<description>"
  echo "-"
  exit 1
fi

echo "-"
echo "Your branch name is OK 😎"
echo "-"

npm run test
