# Run CI for pull request
name: Pull Request

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - develop

env:
  NODE_VERSION: 22.x

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - uses: bahmutov/npm-install@v1

      - name: Lint Application
        run: npm run lint

      - name: Check formatting (Prettier)
        run: npm run format

      - name: Lint styles (Stylelint)
        run: npm run stylelint

      - name: Run tests
        run: npm run test

      - name: Build
        run: npm run build
